name: Maven CI
 
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
 
jobs:
  build:
    uses: ./.github/workflows/maven-reusable.yml
    with:
      project_path: my-app
      java_versions: "17"
      run_tests: true
