name: reusable-maven-build
 
on:
  workflow_call:
    inputs:
      project_path:
        type: string
        required: true
      java_versions:
        type: string
        default: "17"
      run_tests:
        type: boolean
        default: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Diagnose greeting source
        run: |
         echo "Repo branch: $GITHUB_REF"
         echo "Searching for 'Hello,World!' (no space) under my-app:"
         grep -R --line-number "Hello,World!" my-app || echo "Not found"
         echo "Show App.java:"
         sed -n '1,120p' my-app/src/main/java/com/example/App.java  
 
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_versions }}
          distribution: temurin
          cache: maven
 
      - name: Build with Maven
        working-directory: ${{ inputs.project_path }}
        run: |
          if ${{ inputs.run_tests }}; then
            mvn -B -U -Dstyle.color=always clean package
          else
            mvn -B -U -Dstyle.color=always-DskipTests=true clean package
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: maven-build
         path: ${{ inputs.project_path }}/target/*.jar
         if-no-files-found: warn
          
