name: reusable-maven-build
 
on:
  workflow_call:
    inputs:
      project_path:
        description: "Path to the Maven module (folder containing pom.xml)"
        type: string
        required: true
      java_versions:
        description: "Comma-separated JDK versions"
        type: string
        default: "17"
      run_tests:
        description: "Run tests (true/false)"
        type: boolean
        default: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_versions }}
          distribution: temurin
          cache: maven
 
      - name: Build with Maven
        working-directory: ${{ inputs.project_path }}
        run: |
          if ${{ inputs.run_tests }}; then
            mvn -B -U clean package
          else
            mvn -B -U clean package-DskipTests=fi
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: maven-build
         path: ${{ inputs.project_path }}/target/*.jar
          
