name: Maven CI
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'     # you can change to '21' if you like
          distribution: 'temurin'
          cache: maven
 
      # Step 3: Build with Maven
      - name: Build with Maven
        working-directory: my-app   # 👈 very important since pom.xml is inside my-app/
        run: mvn -B package --file pom.xml
 
      # Step 4: Upload build artifacts (optional but useful)
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: my-app/target/*.jar
