name: Maven CI
 
on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        java: [17, 21]
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
 
      - name: Show files (debug)
        run: ls -R .
      
      - name: Build with Maven
        run: mvn -B clean package
        working-directory: ./my-app   # 👈 tell GitHub Actions where pom.xml is
 
      - name: Run tests
        run: mvn -B test
        working-directory: ./my-app
 
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: myapp-artifacts-jdk${{ matrix.java }}
          path: ./my-app/target/*.jar)" >> $GITHUB_STEP_SUMMARY
          echo "- Path: \`${{ env.WORKDIR }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Ref:  \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
