name: reusable-maven-build
 
on:
  workflow_call:
    inputs:
      project_path:
        type: string
        required: true
      run_tests:
        type: boolean
        default: true
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          
