name: Maven CI
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'     # you can change to '21' if you like
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: my-app   # 👈 very important since pom.xml is inside my-app/
        run: mvn -B package --file pom.xml
 
      - name: Upload JAR
        uses: actions/upload-artifact@v4 # ✅ upgraded from v3 → v4
 
        with:
          name: my-app-jar
          path: my-app/target/*.jar
