name: reusable-maven-build
 
on:
  workflow_call:
    inputs:
      project_path:
        type: string
        required: true
      run_tests:
        type: boolean
        default: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'     # <- THIS must be present
          cache: maven
 
      - name: Build with Maven
        working-directory: ${{ inputs.project_path }}
        run: |
          if ${{ inputs.run_tests }}; then
            mvn -B -U -Dstyle.color=always clean package
          else
            mvn -B -U -Dstyle.color=always -DskipTests=true clean package
          fi
 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: ${{ inputs.project_path }}/target/*.jar
          if-no-files-found: warn
