 
name: Maven CI
 
on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
 
env:
  PROJECT_PATH: my-app   # 👈 your pom.xml lives in this folder
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Show files (debug)
        run: |
          echo "Repo root:"
          ls -la
          echo "----"
          echo "Project path ($PROJECT_PATH):"
          ls -la "$PROJECT_PATH"
 
      - name: Verify pom.xml exists
        run: |
          test -f "$PROJECT_PATH/pom.xml" || {
            echo "::error::pom.xml not found at $PROJECT_PATH"
            exit 1
          }
 
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
 
      # Build + test + package; capture full log for later upload if needed
      - name: Build with Maven (tests on)
        shell: bash
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          set -euo pipefail
          mvn -B -U -Dstyle.color=always clean package | tee maven-build.log
 
      - name: Upload JAR/WAR artifacts
        uses: actions/upload-artifact@v4
        with:
         name: app-artifacts-jdk${{ matrix.java }}
         path: |
            ${{ env.PROJECT_PATH }}/**/target/*.jar
            ${{ env.PROJECT_PATH }}/**/target/*.war
         if-no-files-found: warn
 
      - name: Upload test reports (Surefire/Failsafe)
        uses: actions/upload-artifact@v4
        with:
         name: test-reports-jdk${{ matrix.java }}
         path: |
            ${{ env.PROJECT_PATH }}/**/target/surefire-reports/**
            ${{ env.PROJECT_PATH }}/**/target/failsafe-reports/**
         if-no-files-found: ignore
 
      # If anything failed above, ship the Maven log so you can read it
      - name: Upload Maven build log (only on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-log-jdk${{ matrix.java }}
          path: ${{ env.PROJECT_PATH }}/maven-build.log
          if-no-files-found: ignore
